name: Build Docker image
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Build image
        run: |
          docker build --tag ${{ github.repository }}:latest .
      - name: Run image
        run: |
          docker run --rm ${{ github.repository }}:latest --version
