name: Build Docker image
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Build image
        uses: docker/build-push-action@v5
        with:
          push: false
          tags: ${{ github.repository }}:latest
      - name: Run image
        run: |
          docker run --rm ${{ github.repository }}:latest /bin/sh -c "/usr/local/bin/cdk --version"
      - name: Compose image
        run: |
          docker-compose up -d --build
          docker-compose exec -T cdk touch 1001.txt
          docker-compose down
          stat -c %u 1001.txt | grep 1001
